vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /imgs/galerie
            upload_destination: '%kernel.project_dir%/public/imgs/galerie'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
